//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public int ID_payment { get; set; }
        public int ID_worker { get; set; }
        public double sum_p { get; set; }
        public System.DateTime date_p { get; set; }
    
        public virtual workers workers { get; set; }
    }
}
